/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bitcoin_NativeSha256 */

#ifndef _Included_org_bitcoin_NativeSha256
#define _Included_org_bitcoin_NativeSha256
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bitcoin_NativeSha256
 * Method:    secp256k1_sha256
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_bitcoin_NativeSha256_secp256k1_1sha256
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
